name: OceanusMCKitPVP
version: ${project.version}
main: oceanusmckitpvp.OceanusMCKitPVP
api-version: 1.16

commands:
  build:
    description: Toggles Build Mode
  setmaxhealth:
    desciption: Sets the max Health