name: OceanusMCKitPVP
version: ${project.version}
main: oceanusmckitpvp.OceanusMCKitPVP
api-version: 1.16
depend: ["PlaceholderAPI"]

commands:
  build:
    description: Toggles Build Mode
  ocsetmaxhp:
    desciption: Sets the max Health
  cleardogs:
    desciption: None
