name: Release Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: Kitpvp
        path: /home/runner/work/oceanusmc-plugins/oceanusmc-plugins/target/OceanusMC-KitPVP-1.0.jar
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/oceanusmc-plugins/oceanusmc-plugins/target/OceanusMC-KitPVP-1.0.jar
        asset_name: Kitpvp-1.0
        tag: ${{ github.ref }}
        overwrite: false
        body: "Recent Release"
